OmniSharp/csharp-language-server-protocol

src/JsonRpc/InputHandler.cs, src/JsonRpc/OutputHandler.cs, test/JsonRpc.Tests/OutputHandlerTests.cs
Sorry, I'm not familiar with pull requests and so I wasn't able to provide separate ones per issue.
Additionally you might want to call Dispose() in test/JsonRpc.Tests/OutputHandlerTests.cs, but that looked to invasive to me.
Best regards, Martin
=> Fix for Issue #3 and #4

src/Server/LanguageServer.cs, src/Server/LanguageServerLogger.cs
Resolves OmniSharp/csharp-language-server-protocol#69.
=> Implement configurable log level for language server's built-in logger.

src/Protocol/Models/DocumentSelector.cs, src/Server/HandlerCollection.cs, src/Server/Matchers/ResolveCommandMatcher.cs, test/Lsp.Tests/HandlerResolverTests.cs, test/Lsp.Tests/Matchers/ResolveCommandMatcherTests.cs
Set descriptor key when post-processing if resolve hander is the same as the command handler.
=> Improve resolve handler matching

.gitignore, .travis.yml, .vscode/settings.json, Common.Build.props, build.cake, sample/SampleServer/TextDocumentHandler.cs, src/Client/LanguageClient.cs, src/Client/Protocol/LspConnection.cs, src/JsonRpc/HandlerCollection.cs, src/JsonRpc/JsonRpc.csproj, src/JsonRpc/RequestRouter.cs, src/JsonRpc/Serializer.cs, src/JsonRpc/ServiceCollectionExtensions.cs, src/Server/Handlers/CancelRequestHandler.cs, src/Server/Handlers/ExitHandler.cs, src/Server/Handlers/ShutdownHandler.cs, src/Server/LanguageServer.cs, test/Client.Tests/Client.Tests.csproj, test/Directory.Build.props, test/Directory.Build.targets, test/JsonRpc.Tests/JsonRpc.Tests.csproj, test/Lsp.Tests/ExecuteCommandSyncHandlerExtensions.cs, test/Lsp.Tests/Lsp.Tests.csproj, test/Lsp.Tests/LspRequestRouterTests.cs, test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequest.cs, test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequestTResponse.cs
Using the JsonRpc library is difficult without these...
This will hopefully get some more fixes today and get lsp all working as well... once I get back from dinner!
=> [wip] export more public types

.vscode/settings.json, src/JsonRpc/HandlerCollection.cs, src/JsonRpc/IJsonRpcServer.cs, src/JsonRpc/InputHandler.cs, src/JsonRpc/JsonRpc.csproj, src/JsonRpc/JsonRpcServer.cs, src/JsonRpc/JsonRpcServerOptions.cs, src/JsonRpc/JsonRpcServerOptionsExtensions.cs, src/JsonRpc/Server/JsonRpcException.cs, src/JsonRpc/Server/JsonRpcInvalidRequestException.cs, src/Server/LanguageServer.cs, src/Server/LspHandlerDescriptorHelpers.cs, src/Server/Server.csproj, src/Server/SupportedCapabilities.cs
=> Added json rpc server builder

src/JsonRpc/JsonRpcServer.cs, src/Server/LanguageServer.cs
=> load handlers... because that makes sense!

Common.Build.props, src/Client/Client.csproj, src/JsonRpc/JsonRpc.csproj, src/Protocol/Protocol.csproj, src/Server/LanguageServer.cs, src/Server/Server.csproj
=> Added nuget metadata

src/Server/InitializeDelegate.cs, src/Server/LanguageServer.cs
- Makes it possible to register new handlers during initialization phase.
=> Pass ILanguageServer instance in InitializeDelegate

src/Protocol/Document/Client/DocumentSymbolExtensions.cs, src/Protocol/Document/Server/IDocumentSymbolHandler.cs, src/Protocol/Models/DocumentSymbolInformationOrDocumentSymbolContainer.cs, src/Protocol/Models/DocumentSymbolParams.cs
ping @david-driscoll @tintoy 
Fixes #122
=> GH122: DocumentSymbol returns DocumentSymbol[] or SymbolInformation[]

src/Protocol/Document/Server/ICodeActionHandler.cs, test/Lsp.Tests/LspRequestRouterTests.cs, test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequestTResponse.cs, test/Lsp.Tests/Models/CodeActionRegistrationOptionsTests.cs, test/Lsp.Tests/Models/CodeActionRegistrationOptionsTests_$SimpleTest.json
=> (GH-136) Corrected IRegistration definition

src/Protocol/Models/Color.cs
=> RGB values for colors are now represented using floats

src/JsonRpc/Serialization/Converters/ClientResponseConverter.cs
=> Always return result property on success

src/Server/LanguageServer.cs
- For in-proc scenarios the pattern for initializing the language server involves calling PreInit, and then manually calling Initialize. For example that's done here: https://github.com/dotnet/aspnetcore-tooling/pull/1628/files#diff-9327c1670bd2b8bebc131b7dd8e1857bR53
- Memoized the Initialize task to ensure that callign it multiple times only ever initializes once.
- Moved the Initialize method up to ensure it sat next to other public methods.
=> Expose Initialize as a public method on ILanguageServer.

src/Protocol/Client/Capabilities/CompletionItemCapability.cs, src/Protocol/Client/Capabilities/PublishDiagnosticsCapability.cs, src/Protocol/Models/CompletionItemTag.cs, src/Protocol/Serialization/ContractResolver.cs, src/Protocol/Serialization/Converters/SupportsConverter.cs, test/Lsp.Tests/Capabilities/Client/CompletionItemCapabilityTests.cs, test/Lsp.Tests/Capabilities/Client/PublishDiagnosticsCapabilityTests.cs
This was done through the UI... there may be actual code breaks that I can get to.
=> Change TagSupport to use Supports<> helper class

src/Protocol/DocumentUri.cs, test/Lsp.Tests/DocumentUriTests.cs
=> Added support for more generic uris

src/JsonRpc/CompositeHandlersManager.cs, test/JsonRpc.Tests/CompositeHandlersManagerTests.cs, test/JsonRpc.Tests/TestLanguageServerRegistry.cs
There was an issue with the handler manager not working in OmniSharp and I discovered I missed a bug here... fixing to push another beta.
=> Fixed bug in composite handler managers and added unit tests

src/JsonRpc/InputHandler.cs, src/Protocol/Document/IDocumentFormattingHandler.cs, src/Protocol/Document/IDocumentOnTypeFormattingHandler.cs, src/Protocol/Document/IDocumentRangeFormattingHandler.cs, src/Protocol/Document/IPrepareRenameHandler.cs, src/Protocol/Document/IRenameHandler.cs, src/Protocol/Document/IWillSaveWaitUntilTextDocumentHandler.cs, src/Protocol/Models/WorkspaceFolder.cs, src/Protocol/Window/IShowMessageRequestHandler.cs, src/Protocol/Workspace/IDidChangeConfigurationHandler.cs, src/Protocol/Workspace/IDidChangeWatchedFilesHandler.cs, test/Lsp.Tests/RequestProcessIdentifierTests.cs
notifications should not cancel instead they should complete in order as expected (as they are typically fire and forget anyway)
=> notifications should not cancel

Directory.Build.targets, azure-pipelines.nuke.yml
=> fix ci issue

src/Protocol/Models/FormattingOptions.cs, test/Lsp.Tests/Models/FormattingOptionsTests.cs
=> Fix exception thrown by disctionary inside formatting options

src/JsonRpc/InputHandler.cs, test/Lsp.Tests/Integration/ErroringHandlingTests.cs, test/Lsp.Tests/Integration/LanguageServerConfigurationTests.cs
=> Fixed case where if serialization fails the server will die silently.

Directory.Packages.props
=> Update dependency Serilog.Extensions.Logging to v7

.build/Build.cs, .build/Solution.cs, .github/workflows/ci.yml
Following https://github.com/RocketSurgeonsGuild/Nuke/pull/954
=> Use new WorkingDirectory property for RunStep

Directory.Packages.props, test/Generation.Tests/snapshots/JsonRpcGenerationTests.Should_Report_Diagnostic_If_Missing_Information.verified.txt, test/Generation.Tests/snapshots/JsonRpcGenerationTests.Supports_Generating_Notifications_And_Infers_Direction_DidChangeTextHandler.verified.txt, test/Generation.Tests/snapshots/JsonRpcGenerationTests.Supports_Generating_Notifications_And_Infers_Direction_ExitHandler.verified.txt, test/Generation.Tests/snapshots/JsonRpcGenerationTests.Supports_Generating_Requests_And_Infers_Direction.verified.txt
=> Fix verify update
