OmniSharp/csharp-language-server-protocol

src/JsonRpc/OutputHandler.cs

Sorry for the trouble. I noticed not only until today, that my VS2017 only ran the Lsp.Tests but not the JsonRpc ones. I overlooked (1) that cancelling the token causes an ex when canceled and (2) that the CancellationTokenSource needs to be Disposed as well.
Martin

Fix failing test

---

sample/SampleServer/Program.cs
src/Lsp/Abstractions/IAwaitableTermination.cs
src/Lsp/Handlers/ShutdownHandler.cs
src/Lsp/LanguageServer.cs

The objective was to replace the never ending `await new TaskCompletionSource<object>().Task;` with an awaitable Task that would complete eventually: `await server.WasShutDown;` (I'd prefer `await server.Shutdown;` but that name was already taken by the event).
So I moved the `TaskCompletionSource` down to the `IShutdownHandler` that knows when a shutdown happens. Sorry, no test for that b/c I didn't find any test for `LanguageServer`.
Martin

Awaiting the Shutdown of a LanguageServer

---

sample/SampleServer/Program.cs
src/JsonRpc/Connection.cs
src/JsonRpc/InputHandler.cs
src/JsonRpc/OutputHandler.cs
src/Lsp/LanguageServer.cs
test/JsonRpc.Tests/InputHandlerTests.cs
test/JsonRpc.Tests/OutputHandlerTests.cs

Hence we can't use TextReaders and TextWriters in In/OutputHandlers, because otherwise reading chars when there is only a bytes count would be really hard. So I converted everything to streams plus UTF8 Encoding methods plus some test enhancements.
This change is _important_, because otherwise there is _no_ parsing of text containing non-ASCII characters, which is quite common outside of the US ;-) With it, I can now parse a real Coco/R grammar with a real example :-)
Note: This fix is based on the _current_ OmniSharp/master. As it is some fixes behind, I expect some manual merging.
Martin

BugFix: content-length is counted in bytes

---

src/JsonRpc/InputHandler.cs
test/JsonRpc.Tests/InputHandlerTests.cs

Since you allocate an exclusive background thread for reading, it should be used in that way. Fix+Test.
Martin

ProcessInputThread should be sync

---

src/Lsp/Models/TextDocumentItem.cs
test/Lsp.Tests/Models/DidOpenTextDocumentParamsTests_$SimpleTest.json
test/Lsp.Tests/Models/TextDocumentItemTests_$SimpleTest.json

TextDocumentItem inherits it's Uri from TextDocumentIdentifier now, just as several other classes with an Uri.  Tests had to be adapted, b/c the results are only JSON-functional equivalent to the original ones. I guess, that's acceptable.
It would be even better to have an Interface for things that have a read-only Uri instead of a base class: `IHaveAUri`.

TextDocumentItem inheritance

---

src/JsonRpc/JsonRpc.csproj
src/Lsp/LanguageServer.cs

As noted by LSP protocol docs, clients do not have to support this:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-register-capability
And if the client does not support this, it currently causes LanguageServer.Initialize to hang (since the resulting exception is not handled correctly).

Skip dynamic registration of server capabilities if client does not support it

---

sample/SampleServer/Program.cs
src/JsonRpc/IJsonRpcHandler.cs
src/Lsp/Abstractions/IHandlerCollection.cs
src/Lsp/HandlerCollection.cs
src/Lsp/HandlerDescriptor.cs
src/Lsp/Handlers/CancelRequestHandler.cs
src/Lsp/Handlers/ExitHandler.cs
src/Lsp/Handlers/ShutdownHandler.cs
src/Lsp/LanguageServer.cs
src/Lsp/Models/DocumentFilter.cs
src/Lsp/Models/DocumentSelector.cs
test/Lsp.Tests/HandlerResolverTests.cs
vscode-testextension/package-lock.json
vscode-testextension/src/extension.ts

This has a breaking change, which adds `Key` to `IJsonRpcHandler` so that it can be used in combination with `DocumentSelector` to select the best handlers.

Update handler collection to support many handlers of a type

---

src/JsonRpc/Client/Request.cs
src/JsonRpc/Reciever.cs

Specific fix for OmniSharp/csharp-language-server-protocol#24 (a more general fix will be offered as a separate PR).

Avoid NullReferenceException if "params" property is null.

---

src/Lsp/HandlerCollection.cs
src/Lsp/ImmutableDisposable.cs
src/Lsp/LanguageServer.cs

Try to fix issue with handlers getting registered twice

---

src/Lsp/HandlerDescriptor.cs
test/Lsp.Tests/HandlerResolverTests.cs

Added new equals and additional tests for HandlerDescriptor

---

src/Client/Processes/NamedPipeServerProcess.cs
src/Client/Protocol/LspConnection.cs
test/Client.Tests/ClientTests.cs
test/Client.Tests/ConnectionTests.cs
test/Client.Tests/Logging/TestOutputLogger.cs
test/Client.Tests/TestBase.cs

Hey - I'm starting to add more tests for the LSP client.

Add request-level tests for LspConnection

---

.gitignore
src/Lsp/Abstractions/IHanderMatcherCollection.cs
src/Lsp/Abstractions/IHandlerMatch.cs
src/Lsp/Capabilities/Server/ExecuteCommandOptions.cs
src/Lsp/ClientCapabilityProvider.cs
src/Lsp/HandlerMatcherCollection.cs
src/Lsp/LanguageServer.cs
src/Lsp/Lsp.csproj
src/Lsp/LspRequestRouter.cs
src/Lsp/Matchers/ExecuteCommandMatcher.cs
src/Lsp/Matchers/TextDocumentMatcher.cs
src/Lsp/Models/Command.cs
src/Lsp/Models/DidChangeTextDocumentParams.cs
src/Lsp/Models/DidOpenTextDocumentParams.cs
src/Lsp/Models/ExecuteCommandParams.cs
test/Lsp.Tests/ClientCapabilityProviderTests.cs
test/Lsp.Tests/ExecuteCommandSyncHandlerExtensions.cs
test/Lsp.Tests/Lsp.Tests.csproj
test/Lsp.Tests/LspRequestRouterTests.cs
test/Lsp.Tests/Matchers/ExecuteCommandHandlerMatcherTests.cs
test/Lsp.Tests/Matchers/TextDocumentMatcherTests.cs
test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequest.cs
test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequestTResponse.cs
test/Lsp.Tests/Models/CodeLensTests.cs
test/Lsp.Tests/Models/CommandTests.cs
test/Lsp.Tests/Models/ExecuteCommandParamsTests.cs

Added Reduce method to execute at single action from a collection
Changed Command Arguments to JArray
Changed ExecuteCommandParams to JArray
Added GetExecuteCommand in LSPRequestRouter
Added ClientCapabilityProviderFixture
Added IHandlerMatcher to match handlers to parameters
Added Tests

Modified ExecuteCommandHandler parsing on the LSPRequestRouter

---

src/Client/Dispatcher/LspDispatcher.cs
src/Client/Handlers/DelegateEmptyNotificationHandler.cs
src/Client/Handlers/DelegateHandler.cs
src/Client/Handlers/DelegateNotificationHandler.cs
src/Client/Handlers/DelegateRequestHandler.cs
src/Client/Handlers/DelegateRequestResponseHandler.cs
src/Client/Handlers/DynamicRegistrationHandler.cs
src/Client/Handlers/IHandler.cs
src/Client/Handlers/IInvokeNotificationHandler.cs
src/Client/Handlers/IInvokeRequestHandler.cs
src/Client/Handlers/JsonRpcEmptyNotificationHandler.cs
src/Client/Handlers/JsonRpcHandler.cs
src/Client/Handlers/JsonRpcNotificationHandler.cs
src/Client/LanguageClient.cs
src/Client/Protocol/LspConnection.cs
test/Client.Tests/ClientTests.cs
test/Client.Tests/ConnectionTests.cs
test/Client.Tests/HandlerTests.cs

This moves the deserialisation of payloads out of handlers and into the calling code (`LspDispatcher`).

 Move payload deserialisation out of handlers

---

src/Server/Matchers/TextDocumentMatcher.cs

Removed call to `GetType()` on something that's already a `Type` :)
Fixes OmniSharp/csharp-language-server-protocol#54.

Log correct type for handler interface.

---

src/Client/Protocol/ClientMessage.cs
src/Client/Protocol/LspConnection.cs

This is necessary for "container" return types that contain multiple values because they will be serialised as arrays instead of objects.
OmniSharp/csharp-language-server-protocol#56

Enable client to handle array-type responses

---

src/Client/Dispatcher/LspDispatcher.cs
src/Client/Protocol/ServerMessage.cs

Another place the client needs to be able to  handle params / responses that may be array (or other non-object) types.
Relates to OmniSharp/csharp-language-server-protocol#56.

Fix client-level handling of non-object params / results in server messages

---

src/Server/LanguageServer.cs

This enables consumers who have their own logging mechanisms to suppress the built-in log sink and substitute their own one(s).

Enable opting out of built-in logger provider.

---

src/Server/Handlers/ShutdownHandler.cs

The shutdown handler needs to run asynchronously because otherwise the server may deadlock on shutdown (server disposal disposes the `ProcessScheduler`, which attempts to join its own dispatcher thread; if we're not asynchronous, then the thread that's currently running is blocking that dispatcher thread).

Ensure shutdown handler runs asynchronously

---

LanguageServer/Protocol/Client/Capabilities/FoldingRangeCapability.cs
LanguageServer/Protocol/Document/Server/IFoldingRangeHandler.cs
LanguageServer/Protocol/Models/FoldingRange.cs
LanguageServer/Protocol/Models/FoldingRangeKind.cs
LanguageServer/Protocol/Models/FoldingRangeRequestParam.cs
LanguageServer/Protocol/Server/Capabilities/FoldingRangeProviderOptions.cs

Implements the `textDocument/foldingRange` request.
Title contains `WIP` because I'm yet to be able to make vscode work with it (haven't tried other editors).
Thank you all for this amazing implementation of the protocol.

[WIP] Start implementing code folding provider

---

src/Client/Protocol/ServerMessage.cs
src/JsonRpc/Client/Notification.cs
src/JsonRpc/Client/Request.cs
src/JsonRpc/Client/Response.cs
src/JsonRpc/RpcError.cs
src/JsonRpc/RpcErrorConverter.cs
src/JsonRpc/Server/Notification.cs
src/JsonRpc/Server/Request.cs
src/JsonRpc/Server/ResponseBase.cs
test/JsonRpc.Tests/OutputHandlerTests.cs
test/Lsp.Tests/Messages/ServerErrorEndTests_$SimpleTest.json
test/Lsp.Tests/Messages/ServerErrorStartTests_$SimpleTest.json
test/Lsp.Tests/Messages/ServerNotInitializedTests_$SimpleTest.json
test/Lsp.Tests/Messages/UnknownErrorCodeTests_$SimpleTest.json

Fixes #98 
Instead of serializing out `{"jsonrpc": "2.0", "result": 19, "id": 1}` as per https://www.jsonrpc.org/specification we've been serializing `{"protcolVersion": "2.0", "result": 19, "id": 1}`.  Talk about a WTF moment...

Bug/gh #98

---

src/Server/ILanguageServer.cs

@david-driscoll you recently exposed services on `LanguageServer`, I think it would be wise to also expose it through the interface in order to avoid unnecessary casts.

Expose service provider through ILanguageServer interface also.

---

src/Protocol/Models/FailureHandlingKind.cs

Tried out the betas with an updated LSP client and got this exception:
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "textOnlyTransactional" to type 'System.Nullable`1[OmniSharp.Extensions.LanguageServer.Protocol.Models.FailureHandlingKind]'. Path 'params.capabilities.workspace.workspaceEdit.failureHandling', line 1, position 349. ---> System.ArgumentException: Requested value 'textOnlyTransactional' was not found.
```

Fixes FailureHandlingKind after LSP spec update

---

src/Server/ClientCapabilityProvider.cs
test/Lsp.Tests/ClientCapabilityProviderTests.cs

Support Client capabilities implementing ConnectedCapability<> multiple times

---

src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs
src/Server/LanguageServer.cs
test/Lsp.Tests/Capabilities/Client/ClientCapabilitiesTests.cs
test/Lsp.Tests/Capabilities/Client/ClientCapabilitiesTests_$SimpleTest.json
test/Lsp.Tests/FluentAssertionsExtensions.cs
test/Lsp.Tests/Models/InitializeParamsTests.cs
test/Lsp.Tests/Models/InitializeParamsTests_$SimpleTest.json

Fix handling of textDocument/foldingRange

---

sample/SampleServer/Program.cs
sample/SampleServer/TextDocumentHandler.cs
src/Directory.Build.props
src/JsonRpc/JsonRpc.csproj
src/Protocol/Document/ITextDocumentIdentifier.cs
src/Protocol/ILanguageServerRegistry.cs
src/Server/Abstractions/IHandlerCollection.cs
src/Server/HandlerCollection.cs
src/Server/HandlerCollectionExtensions.cs
src/Server/LanguageServer.cs
src/Server/LanguageServerOptions.cs
src/Server/LspHandlerDescriptorDisposable.cs
src/Server/LspRequestRouter.cs
src/Server/Matchers/TextDocumentMatcher.cs
src/Server/TextDocumentIdentifiers.cs
test/Lsp.Tests/ClientCapabilityProviderFixture.cs
test/Lsp.Tests/ClientCapabilityProviderTests.cs
test/Lsp.Tests/HandlerResolverTests.cs
test/Lsp.Tests/LanguageServerTests.cs
test/Lsp.Tests/Lsp.Tests.csproj
test/Lsp.Tests/LspRequestRouterTests.cs
test/Lsp.Tests/Matchers/TextDocumentMatcherTests.cs
test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequest.cs
test/Lsp.Tests/MediatorTestsRequestHandlerOfTRequestTResponse.cs
test/Lsp.Tests/TextDocumentSyncHandlerExtensions.cs
vscode-testextension/package-lock.json
vscode-testextension/package.json

This contains two fixes.
1) Fixed the problem where requests were not being routed correctly.  
2) Adds an example folding range, to ensure that it works.
Also I've done a small refactor around `ITextDocumentIdentifier` previously this was only integrated in `ITextDocumentSyncHandler`, if you didn't register a `ITextDocumentSyncHandler` we would never catch any file registrations, because we would have way to identify a file.
I have left `ITextDocumentIdentifier` as a member of the `ITextDocumentSyncHandler` interface but I have added the ability to add your own `ITextDocumentIdentifier` instances, which will then be used when trying to identify files by `Uri`.

Fix language server not working with the latest beta

---

src/Protocol/Serialization/Converters/BooleanOrConverter.cs
test/Lsp.Tests/Models/InitializeResultTests.cs
test/Lsp.Tests/Models/InitializeResultTests_$BooleanOrTest.json

- Serialize object type correctly
- Fixes #159
With #156 and #148 we will now see `BooleanOr<T>` serializing `T` as class, which bubbled up a bug in the converter. We where trying to feed a `JValue` with the object directly, which made JSON.NET throw an exception. Best is to probably have the serializer serialize it directly into the writer.

GH159: Fixes BooleanOrConverter

---

src/Dap.Protocol/Requests/InitializeResponse.cs
src/JsonRpc/Serialization/DebugAdapterConverters/DapClientResponseConverter.cs

So far this includes:
* A fix to the `InitializeResponse` payload
* temporarily setting `success` to `true` - we should set this based on the execution of the handler, but this unblocks me for now

Misc dap fixes

---

src/JsonRpc/JsonRpcServer.cs

The reciever is added a few lines up on line 87 so we don't want to replace that with a new instance of the `Receiver` class which wouldn't work for the debug adapter.
side note... isn't it spelled `receiver`? (`i` before `e` except after `c` 😄)

remove extra Reciever

---

src/JsonRpc/InputHandler.cs
src/JsonRpc/OutputHandler.cs
src/JsonRpc/ProcessScheduler.cs

`JsonRpcServer.Dispose()` now works. It use to throw an exception deep from within `InputHandler` and `OutputHandler`.
Not sure if this needs any test changes but I think the tests need fixing anyway from previous PRs.

JsonRpcServer now disposable

---

src/JsonRpc/DapReciever.cs

This was needed for the `configurationDone` message which is a Client->Server request that has no params.
It was failing to cast an EmptyResponse to the ConfigurationDone request.

switch null to new JObject so it can still be parsed into the right type

---

src/JsonRpc/Serialization/DebugAdapterConverters/DapRpcErrorConverter.cs

Now in my handler I can do:
```csharp
throw new RpcErrorException(0, "A positive integer must be specified for the processId field.");
```
and then I get:
One thing that does concern me is that the [DAP spec says that `command` is required](https://microsoft.github.io/debug-adapter-protocol/specification#Base_Protocol_Response) in Response bodies, but this functionality works as I want so I'm going to just ignore that detail for now as it might actually be optional.

fix up WriteJson for DAP error handling

---

src/Protocol/Models/DiagnosticRelatedInformation.cs
test/Lsp.Tests/Models/DiagnosticTests.cs
test/Lsp.Tests/Models/DiagnosticTests_$RelatedInformationTest.json

This will change the return of the DiagnosticRelatedInformation.Location property from string to Location.

Changes for #175 to return a Location object for diagnostic related information

---

src/Server/LanguageServer.cs

Noticed we had duplicate code in `PreInit` and `From`. Let's use ´PreInit` in `From` in order to avoid divergence in the future between these two methods.

Remove duplicate code

---

src/Client/Clients/TextDocumentClient.SignatureHelp.cs
test/Client.Tests/ClientTests.cs

See #170. Added SignatureHelp support.

Added SignatureHelp support.

---

sample/SampleServer/Program.cs
sample/SampleServer/SampleServer.csproj
sample/SampleServer/TextDocumentHandler.cs
src/JsonRpc/RequestRouterBase.cs
src/Server/LanguageServer.cs
src/Server/LanguageServerOptions.cs
src/Server/LanguageServerOptionsExtensions.cs
test/Lsp.Tests/LanguageServerTests.cs
vscode-testextension/.vscode/tasks.json
vscode-testextension/src/extension.ts

- Expose ILoggingBuilder instead of accepting a ILoggerFactory
Some open questions. How to maintain backwards compatibility, or should we?

Refactor logging  +semver:minor

---

sample/SampleServer/Program.cs
sample/SampleServer/TextDocumentHandler.cs
src/Server/LanguageServer.cs
src/Server/LanguageServerOptions.cs
src/Server/LanguageServerOptionsExtensions.cs
src/Server/Logging/LanguageServerLogger.cs
src/Server/Logging/LanguageServerLoggerExtensions.cs
src/Server/Logging/LanguageServerLoggerFilterOptions.cs
src/Server/Logging/LanguageServerLoggerProvider.cs
src/Server/Logging/LanguageServerLoggerSettings.cs

replaces `AddDefaultLoggingProvider()` with `.AddLanguageServer()`.
Allows you to pass in a `LogLevel` into `.AddLanguageServer()` (default is Information)

Adds ILoggingBuilder extension for LanguageServer logging.

---

sample/SampleServer/Program.cs
src/Server/Logging/LanguageServerLoggerExtensions.cs

@TylerLeonhardt is this what you wanted?

Allow using global log level as minimum log level for LanguageServerLoggerProvider

---

src/Client/Clients/TextDocumentClient.Definition.cs
src/Client/Clients/TextDocumentClient.DocumentHighlight.cs
src/Client/Clients/TextDocumentClient.DocumentHighlights.cs
src/Client/Clients/TextDocumentClient.FoldingRanges.cs
test/Client.Tests/ClientTests.cs

Added support for Definition, DocumentHighlights, FoldingRanges to TextDocumentClient.

---

src/Server/LanguageServer.cs

- For LSP3 clients the TextDocumentSynchronization kind is always set to none without this. For the VS LSP client this results in language servers never getting any text document synchronization events.

Fix TextDocument synchronization for LSP3

---

src/Protocol/Serialization/Converters/SymbolInformationOrDocumentSymbolConverter.cs
test/Client.Tests/ClientTests.cs

Fix DocumentSymbol Json Converter

---

src/Protocol/Serialization/Converters/CommandOrCodeActionConverter.cs

Fixes OmniSharp/csharp-language-server-protocol#210

Correctly handle CommandOrCodeAction with missing "command" property

---

src/JsonRpc/OutputHandler.cs

- Not all streams auto-flush after write. For instance creating a duplex JsonRpc stream to run the O# server in-proc results in the server never initializing because the flush result is not sent down to the client. For instance: https://github.com/dotnet/aspnetcore-tooling/blob/ed01e6b0d167f0dda61d9cdba226f8844fa1d96e/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs#L49

Flush after writing.

---

_config.yml
src/Protocol/Serialization/Converters/RangeOrPlaceholderRangeConverter.cs
src/Protocol/Serialization/Serializer.cs
test/Lsp.Tests/Capabilities/Server/PrepareRenameTests.cs
test/Lsp.Tests/Capabilities/Server/PrepareRenameTests_$PlaceholderRange.json
test/Lsp.Tests/Capabilities/Server/PrepareRenameTests_$Range.json

This will add a new converter for RangeOrPlaceholderRange to the Serializer. 
@RangeOrPlaceholderRangeConverter
I let `CanRead` return `false` because the client will never send such an object. I also return an empty `RangeOrPlaceholderRange` in case of `Read`. Not sure, perhaps it`s better to return null or throw?
Fixes #214

Fixes #214 by returning LSP conform JSON for prepare rename request

---

README.md

It is not quite obvious what NuGet packages are produced from this repo, so added two badges for the commonly used ones.
Don't know

Added two NuGet badges.

---

src/Protocol/Models/ProgressToken.cs

Copy-pasting the server example causes the app to crash with a StackOverflowException. After hours of trying to debug this, i tracked the issue down to these lines of code. Would appreciate it if the problem was fixed one way or another

Fix StackOverflowException in ProgressToken.Equals

---

src/Client/LanguageClient.cs
src/Client/Protocol/LspConnection.cs

The LanguageClient sends a Shutdown notification. But the LanguageServer expects a request (as per spec), causing a server-side deserialization error.

Add SendEmptyRequest Method for shutdown request

---

Directory.Build.targets
src/JsonRpc/Connection.cs
src/JsonRpc/IScheduler.cs
src/JsonRpc/InputHandler.cs
src/JsonRpc/ProcessScheduler.cs
src/JsonRpc/RequestRouterBase.cs
src/Protocol/Document/Server/ICompletionHandler.cs
src/Server/LanguageServer.cs
src/Server/LanguageServerOptions.cs
src/Server/LanguageServerOptionsExtensions.cs
test/Directory.Build.targets
test/JsonRpc.Tests/DapInputHandlerTests.cs
test/JsonRpc.Tests/InputHandlerTests.cs
test/JsonRpc.Tests/ProcessSchedulerTests.cs

This is to rework the scheduler to achieve a few things:
1) The code has always been a pain point, it works but it's hard to work on.
2) We've never been able to put a hard cap on total number of parallel operations that can happen at a time (number of concurrent requests)
If you don't like observables cover your eyes.
If you like observables and know a slightly better way to fan-in fan-out let me know! 😄 
@TylerLeonhardt what are your thoughts on making completion resolve handler parallel?  Originally I had it serial because it can contain actions and edits but that would get invalidated by another document change anyway.

Rework ProcessScheduler

---

src/JsonRpc/IResponseRouter.cs
src/JsonRpc/IReturning.cs
src/JsonRpc/JsonRpcServer.cs
src/JsonRpc/ResponseRouter.cs
src/Protocol/ClientProxyBase.cs
src/Protocol/Workspace/Client/ExecuteCommandExtensions.cs
src/Server/LanguageServer.cs

This is a quick change related `IResponseRouter`.
Currently if you have a params object and a response object you always have to define the type of both to call `SendRequest`.  This new pattern returns an object lets you define the return type of the request, so it's a little easier to do `SendRequest("somemethod", someParams).Returning<ReturnType>(cancellationToken)`

Refactored IResponseRouter for better type inference

---

src/Protocol/Models/FoldingRangeKind.cs
test/Lsp.Tests/Models/FoldingRangeKindTests.cs

This just needed the `[JsonConverter(typeof(StringEnumConverter))]`.
This should fix https://github.com/PowerShell/vscode-powershell/issues/2700

Fix FoldingRangeKind serialization to be string

---

src/Protocol/DocumentUri.cs
test/JsonRpc.Tests/InputHandlerTests.cs
test/Lsp.Tests/DocumentUriTests.cs
test/Lsp.Tests/Models/ApplyWorkspaceEditParamsTests.cs
test/Lsp.Tests/Models/ApplyWorkspaceEditParamsTests_$NonStandardCharactersTest.json
test/Lsp.Tests/Models/CodeActionParamsTests.cs
test/Lsp.Tests/Models/CodeActionParamsTests_$NonStandardCharactersTest.json
test/Lsp.Tests/Models/CodeLensParamsTests_$NonStandardCharactersTest.json
test/Lsp.Tests/Models/DidChangeTextDocumentParamsTests_$NonStandardCharactersTest.json
test/Lsp.Tests/Models/DidChangeWatchedFilesParamsTests.cs
test/Lsp.Tests/Models/DidChangeWatchedFilesParamsTests_$NonStandardCharactersTest.json

This `EscapeUriString` on the Path and
`EscapeDataString` on the Query and Fragment
It also updates all the tests to reflect that we will receive encoded urls.

URL encode when running ToString()

---

src/Protocol/DocumentUri.Internal.cs
src/Protocol/DocumentUri.cs
test/Lsp.Tests/DocumentUriTests.cs
test/Lsp.Tests/VsCodeDocumentUriTests.cs

This removes any OS forks of logic (which allows non-Windows to handle Windows paths correctly, etc.)
There was also forward slashes instead of backslashes for the:
```
value = $@"\\{uri.Authority}{uri.Path}";
```
line.

misc changes for DocumentUri

---

src/JsonRpc.Generators/Helpers.cs
src/Protocol/Models/ExecuteCommandRegistrationOptions.cs
src/Protocol/Workspace/IExecuteCommandHandler.cs
src/Server/Matchers/TextDocumentMatcher.cs
src/Shared/LspRequestRouter.cs
src/Shared/SharedHandlerCollection.cs
test/JsonRpc.Tests/AutoNSubstitute/TestExtensions.cs
test/Lsp.Tests/FoundationTests.cs
test/Lsp.Tests/Integration/DynamicRegistrationTests.cs
test/Lsp.Tests/Integration/ExecuteCommandTests.cs
test/Lsp.Tests/Integration/InitializationTests.cs
test/Lsp.Tests/Integration/RequestCancellationTests.cs
test/Lsp.Tests/LspRequestRouterTests.cs

* Fixes a bug where if only one command is registered, it's called even if the command that is being executed has a different name.
* Fixes a bug where only one command handler could be registered at a time (effectively).
* Adds a method for executing a `Command` directory on the client (retrieved from completions for example)
* Adds `OnExecuteCommand<T[, [T2, [T3, [T4, [T5, [T6]]]]]>`
* These handlers will automatically deserialize the arguments from the arguments JArray

Commands, bugs, helpers and more!

---

src/Client/LanguageClientRegistrationManager.cs
src/Dap.Protocol/Requests/IAttachHandler.cs
src/Dap.Protocol/Requests/ILaunchHandler.cs
src/Dap.Protocol/Serialization/OptionalAttribute.cs
src/Dap.Shared/DebugAdapterHandlerCollection.cs
src/JsonRpc/HandlerTypeDescriptor.cs
src/JsonRpc/HandlerTypeDescriptorHelper.cs
src/JsonRpc/InputHandler.cs
src/Protocol/Models/ExecuteCommandParams.cs
src/Protocol/Models/IExecuteCommandParams.cs
src/Protocol/Serialization/OptionalAttribute.cs
src/Protocol/Shared/LspHandlerTypeDescriptorHelper.cs
src/Server/Matchers/ExecuteCommandMatcher.cs
src/Shared/LspRequestRouter.cs
src/Shared/SharedHandlerCollection.cs
test/Lsp.Tests/Integration/OverrideHandlerTests.cs
test/Lsp.Tests/Lsp.Tests.csproj

Added support for class based handlers to HandlerTypeDescriptorHelper/LspHandlerTypeDescriptorHelper.
Added unit test demonstrating a custom params / handler pair for Execute Command
Made the OptionalAttribute's public
Added IExecuteCommandParams to allow for custom command execution handlers to work correctly.
fixes: #308

Added support for custom handlers that can replace / work side-by-side with existing handlers

---

test/Generation.Tests/GenerationHelpers.cs

Using GeneratorDriver means you don't need all of that jank.
This is slightly different because it will create a compilation, which the previous code didn't. I've left commented out the line that validates that resulting compilation because three of the tests fail with it left in, but I don't know enough about what the generator is supposed to do to know if thats valid or not.
Feel free to throw this away if it's not helpful :)

Remove jank

---

src/Client/LanguageClientOptions.cs
src/Dap.Client/DebugAdapterClientOptions.cs
src/Dap.Server/DebugAdapterServerOptions.cs
src/Dap.Shared/DebugAdapterHandlerCollection.cs
src/JsonRpc/CompositeHandlersManager.cs
src/JsonRpc/HandlerCollection.cs
src/JsonRpc/HandlersManagerExtensions.cs
src/JsonRpc/IHandlersManager.cs
src/JsonRpc/IJsonRpcHandlerRegistry.cs
src/JsonRpc/InterimJsonRpcServerRegistry.cs
src/JsonRpc/JsonRpcCommonMethodsBase.cs
src/JsonRpc/JsonRpcOptionsRegistryBase.cs
src/JsonRpc/JsonRpcServerOptionsBase.cs
src/Server/LanguageServerOptions.cs
src/Shared/SharedHandlerCollection.cs
test/Dap.Tests/Integration/HandlersManagerIntegrationTests.cs
test/JsonRpc.Tests/TestLanguageServerRegistry.cs
test/Lsp.Tests/Integration/HandlersManagerIntegrationTests.cs

* Added extension method to get all the unique handlers contained in the IHandlersManager
* Renamed link parameter names to better reflect their meaning.
* Added some better exceptions here to help users in the future.

IHandlersManager and Handler linking improvments

---

.build/Build.cs
src/Dap.Testing/DebugAdapterProtocolTestBase.cs
src/Dap.Testing/DebugAdapterServerTestBase.cs
src/JsonRpc.Testing/JsonRpcServerTestBase.cs
src/JsonRpc/JsonRpcServerOptionsBase.cs
src/JsonRpc/ResponseRouter.cs
src/Protocol/LanguageProtocolRpcOptionsBase.cs
src/Server/Logging/LanguageServerLogger.cs
src/Server/Logging/LanguageServerLoggerProvider.cs
src/Shared/LanguageProtocolServiceCollectionExtensions.cs
test/Client.Tests/ClientTests.cs
test/Dap.Tests/Integration/RecursiveResolutionTests.cs
test/JsonRpc.Tests/ResponseRouterTests.cs
test/Lsp.Tests/Integration/DynamicRegistrationTests.cs
test/Lsp.Tests/Integration/LanguageServerLoggingTests.cs
test/Lsp.Tests/Integration/PartialItemTests.cs
test/Lsp.Tests/Integration/RecursiveResolutionTests.cs
test/TestingUtils/AutoNSubstitute/TestLoggerFactory.cs

Pass through logging for language server has not been working, due to the refactor.
And now with tests!

Fixed logging so it works correctly!

---

src/Server/LanguageServerWorkspaceFolderManager.cs
test/Lsp.Tests/Integration/WorkspaceFolderTests.cs

fixed an issue where workspace folders could be null, and this would cause issues

---

src/Server/DefaultLanguageServerFacade.cs
src/Server/LanguageServer.cs
src/Server/LanguageServerHelpers.cs
test/Lsp.Tests/Integration/InitializationTests.cs
test/Lsp.Tests/Integration/WorkspaceFolderTests.cs

Turns out there is a race condition anyway where supported capabilities aren't loaded yet, and wouldn't be detected.

Fixed case where dynamic registration would fail if Register is called before Initialize

---

.build/Solution.cs
.github/workflows/ci.yml
global.json
test/Lsp.Tests/Integration/TypedCodeLensTests.cs
test/Lsp.Tests/Integration/TypedCompletionTests.cs
test/Lsp.Tests/Integration/TypedDocumentLinkTests.cs

https://github.com/actions/setup-dotnet allows side-by-side installs now

Fixed dotnet hack

---

src/Protocol/Document/IDocumentColorHandler.cs
src/Protocol/Models/DocumentColorParams.cs

Fixed document color handler and params

---

src/Server/Configuration/DidChangeConfigurationProvider.cs
src/Server/LanguageServerServiceCollectionExtensions.cs

If you override configuration this removes the meaningless warning.

only emit warning if configuration is in use

---

src/Protocol/Document/IPrepareRenameHandler.cs
test/Lsp.Tests/Integration/RenameTests.cs

ensure prepare rename does not try to register with the client

---

package-lock.json
src/Protocol/Models/Position.Helpers.cs
src/Protocol/Models/Position.cs
src/Protocol/Models/Range.Helpers.cs
src/Protocol/Models/Range.cs
src/Testing/PositionMarker.cs
src/Testing/TestConfigurationProvider.cs
src/Testing/TestContent.cs
src/Testing/TestContentOptions.cs
src/Testing/TestSourceHelpers.cs
test/Lsp.Tests/Models/PositionTests.cs
test/Lsp.Tests/Models/RangeTests.cs
test/Lsp.Tests/Testing/TestContentTests.cs

Ported from vscode.  These are to help when working with and on ranges.

Added some additional helpers for both Range and Position

---

debug-adapter-protocol.sha.txt
language-server-protocol.sha.txt
src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs
src/Protocol/Features/Document/DocumentOnTypeFormattingFeature.cs
src/Protocol/Features/Document/LinkedEditingRangeFeature.cs
src/Protocol/Server/Capabilities/ServerCapabilities.cs
src/Protocol/TextDocumentNames.cs

This proposal has been renamed, this syncs up with that change.

OnTypeRename -> LinkedEditingRange

---

src/JsonRpc.Generators/DelegateHelpers.cs
src/JsonRpc.Generators/Strategies/OnNotificationMethodGeneratorWithRegistrationOptionsStrategy.cs
src/JsonRpc.Generators/Strategies/OnNotificationMethodGeneratorWithoutRegistrationOptionsStrategy.cs
src/Protocol/Features/Window/TelemetryEventFeature.cs
test/Lsp.Tests/Integration/CustomRequestsTests.cs

The property `TelemetryEvent.Data` has been renamed to `ExtensionData` and the type has been changed as well.

Added AllowDerivedRequest support for lsp telemetry event

---

src/Dap.Client/DebugAdapterClientOptions.cs
src/Dap.Protocol/Feature/Requests/InitializeRequestFeature.cs
src/Dap.Protocol/Requests/IInitializeRequestArguments.cs

Fixed json name of adapterID for debug adapter protocol

---

src/Dap.Protocol/Models/ProgressToken.cs
src/Dap.Protocol/Serialization/ProgressTokenConverter.cs
src/Dap.Protocol/Serialization/Serializer.cs
src/JsonRpc.Generators/Contexts/SyntaxSymbol.cs
src/JsonRpc.Generators/GenerateHandlerMethodsGenerator.cs
src/JsonRpc.Generators/Helpers.cs
src/JsonRpc.Generators/Strategies/ExtensionMethodGeneratorStrategy.cs
src/JsonRpc.Generators/Strategies/HandlerGeneratorStrategy.cs
src/JsonRpc.Generators/Strategies/OnRequestMethodGeneratorWithRegistrationOptionsStrategy.cs
src/JsonRpc.Generators/Strategies/OnRequestMethodGeneratorWithoutRegistrationOptionsStrategy.cs
src/JsonRpc.Generators/Strategies/OnRequestTypedResolveMethodGeneratorWithRegistrationOptionsStrategy.cs
src/JsonRpc.Generators/Strategies/OnRequestTypedResolveMethodGeneratorWithoutRegistrationOptionsStrategy.cs
src/JsonRpc.Generators/Strategies/SendMethodRequestStrategy.cs
src/Protocol/Features/Workspace/ExecuteCommandFeature.cs
src/Protocol/Shared/LspHandlerDescriptor.cs
test/Dap.Tests/Integration/ProgressTests.cs
test/Generation.Tests/JsonRpcGenerationTests.cs
test/Lsp.Tests/ClientCapabilityProviderTests.cs
test/Lsp.Tests/FoundationTests.cs
test/Lsp.Tests/Integration/ExecuteTypedCommandTests.cs

Added support for open generic params and handler interfaces.  Added ExecuteCommandParams<>

---

src/Protocol/Shared/LspHandlerDescriptor.cs

See:
- https://github.com/OmniSharp/omnisharp-roslyn/issues/1995
The issue (apparently) is that `LspHandlerDescriptor` is constructed for `DelegatingRequest` that is registered in `LanguageServerHost.cs` (in omnisharp-roslyn) via `r.OnRequest()` here:
https://github.com/OmniSharp/omnisharp-roslyn/blob/b68f146a649bd6b0294894831e08bbd3b802110c/src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs#L310
The constructor attempts to resolve RPC return type based on what generic type is set on `IRequest<T>` that is inherited by `DelegatingRequest`. However `DelegatingRequest` implements both `IRequest` and `IRequest<TResponse>` and LINQ code selects `IRequest<MediatR.Unit>` type as the return value -- while it should be `IRequest<JToken>` for LSP requests (apparently?).
The issue was fixed …

Fix invalid cast issue in omnisharp-roslyn by fixing LspHandlerDescriptor ctor

---

src/Dap.Client/DebugAdapterClient.cs
src/Dap.Protocol/Models/Container.cs
src/Protocol/Models/Container.cs
src/Protocol/Models/StringOrMarkupContent.cs
src/Server/Pipelines/ResolveCommandPipeline.cs
test/Lsp.Tests/CompletionItemKindTests.cs
test/Lsp.Tests/Matchers/ResolveCommandMatcherTests.cs

* Added Container.From
* Do not serialize out the PrivateHandlerId if it's empty
* StringOrMarkupContent implict conversion should be nullable.
cc @NTaylorMullen @333fred

Minor updates.

---

.github/workflows/close-milestone.yml
.github/workflows/draft-release.yml

…nch as been renamed to main which caused the break

fix gittools actions to use the latest tagged release, the master branch as been renamed to main which caused the break

---

.gitignore
src/Dap.Protocol/Feature/Requests/ThreadsFeature.cs

Fixes https://github.com/OmniSharp/csharp-language-server-protocol/issues/566

Fix thread debugging

---

src/Server/LanguageServer.cs

Set server receiver to `initialized` at the end of the `initialize` request

---

.editorconfig
Directory.Build.props
sample/SampleServer/Program.cs
sample/SampleServer/SemanticTokensHandler.cs
sample/SampleServer/TextDocumentHandler.cs
src/Dap.Client/DebugAdapterClient.cs
src/Dap.Testing/DebugAdapterProtocolTestBase.cs
src/JsonRpc/OutputHandler.cs
src/Protocol/Features/Document/CallHierarchyFeature.cs
src/Server/LanguageServer.Shutdown.cs
test/.editorconfig

I enabled the new .NET Analyzer for the project and then used an Editor Config rule to treat CA2007 as an error. This diagnostic is for any awaited task that does not have an explicit trailing `.ConfigureAwait(false)` call, an annoying but very necessary configuration for asynchronous .NET library code (such as OmniSharp).
The bugs caused by these missing calls are strange. In the case of PowerShell Editor Services, an LSP server using OmniSharp and powering the PowerShell Extension for VS Code, it showed up as a hang when the server executed user code that used objects from `System.Windows.Forms`.
This is because that .NET library sets its own synchronization context, which is exactly where `ConfigureAwait(continueOnCapturedContext: false)` comes into play. The default value is `true` …

Treat missing `.ConfigureAwait(false)` as errors (and fix)

---

src/JsonRpc/Receiver.cs

- Without this the `.Value<string>` was exploding attempting to convert to a string.

Fix trace state parsing.

---

src/JsonRpc/InputHandler.cs

Observable.Do() does not catch exceptions from FromAsync(), resulting in a potential unobserved exception.

Fix potential unobserved exception in InputHandler.cs

---

Directory.Build.targets
sample/SampleServer/SampleServer.csproj
src/JsonRpc/JsonRpc.csproj

Removed explicit reference to System.IO.Pipelines see #595

---

.build/.build.csproj
Directory.Packages.props
sample/SampleServer/SampleServer.csproj

Unfortunately `System.Threading.Tasks` v4.7.1 is broken. Its package manifest states that it depends on `System.Threading.Tasks.Extensions` >= v4.5.4 (assembly version v4.2.0.1); however, for some reason it actually requests v4.2.0.0. While neither OmniSharp nor PowerShell Editor Services, the downstream library where this bug appeared, ship that version of the library, it can sometimes be found in the Global Assembly Cache on Windows. When present (due to an installation by some other program), it gets loaded, and then other dependencies (correctly) request v4.2.0.1 which also gets loaded. When both are loaded, a `System.MissingMethodException` is thrown! Specifically the method `ChannelReader.ReadAsync` (from `System.Threading.Tasks`) on the type `Tasks.ValueTask` (provided by …

Fix bug caused by `System.Threading.Tasks` v4.7.1

---

src/JsonRpc/Serialization/SerializerBase.cs

The other option is to update Newtonsoft.Json, which now also sets the maximum depth by default, but this mitigates without having to update.

Set max depth for JSON serializer to mitigate known DOS vulnerability

---

vscode-testextension/package-lock.json
vscode-testextension/package.json
vscode-testextension/src/extension.ts

Update dependency typescript to v5

---

.build/Build.cs
.build/Solution.cs
.github/workflows/ci.yml
.nuke/build.schema.json
vscode-testextension/package-lock.json
vscode-testextension/package.json
vscode-testextension/test/runTest.ts

Should avoid introducing breaking changes in the `vscode-testextension` project and int its `npm` dependencies in particular.

Add npm to CI build

---

src/Protocol/Features/Document/NotebookDocumentSyncFeature.cs
src/Server/Matchers/NotebookDocumentMatcher.cs

Fixes #1066
The `NotebookSelector` type is an array type.
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocumentSyncOptions

Fix NotebookSelector type

---

src/JsonRpc/InputHandler.cs

We are showing warnings/errors in our UI and this would pop up every time a client disconnects (usually by the user). This error should not result in a critical message in the log IMO. What do you think?  
Not 100% about the wording of the message to show in this case though.

Don't log critical message when client disconnect

---

Directory.Packages.props
Directory.Packages.supports.props

Versions 10.x-11.x dropped netstandard2.0 support. Version 12.x requries some deep changes due to how IRequest was redefined.

Update Mediatr to 9.0.0

---

src/Protocol/Features/Window/ShowMessageRequestFeature.cs

Fixes #1117 by adding the interface `ICapability` which should allow it to be used by the `LanguageClientOptions.WithCapability` method.

Add ICapability to ShowMessageRequestClientCapabilities. Fixes #1117

---

src/Protocol/Features/FileOperationsFeature.cs
test/Lsp.Integration.Tests/FileOperationTests.cs
test/Lsp.Integration.Tests/FileOperationsTests.cs

Fix RenameFiles workspace operations

---

Directory.Packages.props
test/Dap.Tests/FoundationTests.cs
test/Lsp.Integration.Tests/FluentAssertionsExtensions.cs
test/Lsp.Tests/FluentAssertionsExtensions.cs
test/Lsp.Tests/FoundationTests.cs
test/Lsp.Tests/Models/PositionTests.cs
test/TestingUtils/RecordExtensions.cs
test/TestingUtils/RecordStructuralEqualityEquivalencyStep.cs

Fix FluentAssertions after major update

---

Directory.Packages.props

Fix serilog update

---

.config/dotnet-tools.json

Move to `dotnet-outdated-tool` as `dotnet-outdated` is obsolete and generates now some signature issues on the macos build.

Update dotnet tools
